version: '3'
services:
  golang:
    image: golang:latest
    ports:
      - 8080:80
    volumes:
      - ..:/workspace/golang
    tty: true
    depends_on:
      - db
    restart: always  
    init: true
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db:mysql
    ports:
        - 8888:80
    environment:
        PMA_HOST: mysql
volumes:
  db-store: